# Generated by Django 2.2.8 on 2020-01-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20200128_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Question',
            field=models.CharField(max_length=300),
        ),
    ]
