# Generated by Django 2.2.8 on 2020-01-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20200128_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Option_1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_4',
            field=models.CharField(max_length=60),
        ),
    ]
