# Generated by Django 2.2.8 on 2020-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20200128_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Ans',
            field=models.CharField(max_length=60),
        ),
    ]
